### ISSUE TITLE
[Feature Request] Gacha Rates beyond C6

### ISSUE THREAD

**Issue by iwantcookiesnow** [Tibowl/HuTao#3]
Hello, could you extend the gacha rate calculator to constellations beyond C6? 
Let's say I have enough wishes to get to C6 on a character, but I want to see what my probability is to get another character to C0+, could you implement an option too see the chances for a theoretical C7 and higher?

**Comment by Tibowl** [comment]
You can now have multiple banner targets (outside of having multiple characters, can also mix characters/weapons banners) though it assumes you do them after eachother so chaining 4*'s and 5*'s means doing them after eachother, not in same banner.
